"""empty message

Revision ID: 5ccc58d0b350
Revises: f155a4aef8bc
Create Date: 2020-09-24 23:56:00.144237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ccc58d0b350'
down_revision = 'f155a4aef8bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_tag', sa.Column('default_color', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog_tag', 'default_color')
    # ### end Alembic commands ###
